---
title: "Práctica 0"
author: ''
date: ''
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

El objetivo de esta práctica es repasar algunos conceptos que los alumnos deberían haber aprendido en materias previas. Se recomienda a los alumnos intentar resolver todos los ejercicios y, en caso de tener dudas en alguno, repasar el tema correspondiente. No se le dedicará tiempo en clase a los temas de esta práctica.


1. Redondear a 2 decimales los siguientes números:

a) 0,329
b) 0,324
c) 0,3005
d) 0.2999
e) 0,3049
f) 0,3501
g) 0,3571

2. Hallar el único valor de x e y que resuelve ambas ecuaciones:

$$1=\frac{5-x}{y}$$ 

$$16=\frac{20-x}{y}$$
3. Hallar los únicos valores de x, y, z que resuelven las siguientes ecuaciones:

$$2x+y=9$$
$$y-z+x=4$$
$$x+y+z=10$$
4. Hallar el máximo de la siguiente función:

$$f(x)=\sqrt[2]{\frac{x(1-x)}{10}}$$

5. Resolver las siguientes integrales indefinidas:

a) $\int(3x^2-x)dx$
  
b) $\int(x-4)(x+2)dx$
  
c) $\int(x-3)^2dx$
  
6. Resolver las siguientes integrales definidas:

a) $\int_{1}^{3}3xdx$
  
b) $\int_{0}^{4}(4x^3-1)dx$
  
c) $\int_{5}^{10}(x^2+x+5)dx$
  
7. Obtener las raíces de los siguientes polinomios:

a) $x^3+x^2$
  
b) $2x^4-4x^2$
  
c) $x^2-4$
  
d) $x^2+6x+9$
  
e) $x^2-x-6$